language: android
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
script:
  - sh ./gradlew KalturaClient:build
after_success:
  - if [ -n "$TRAVIS_TAG" ]; then sh ./travis-push-to-bintray.sh; fi
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - gilad.nadav@kaltura.com
    on_success: change
    on_failure: always
