// ===================================================================================================
//                           _  __     _ _
//                          | |/ /__ _| | |_ _  _ _ _ __ _
//                          | ' </ _` | |  _| || | '_/ _` |
//                          |_|\_\__,_|_|\__|\_,_|_| \__,_|
//
// This file is part of the Kaltura Collaborative Media Suite which allows users
// to do with audio, video, and animation what Wiki platfroms allow them to do with
// text.
//
// Copyright (C) 2006-2020  Kaltura Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// @ignore
// ===================================================================================================
package com.kaltura.client.types;

import android.os.Parcel;
import com.google.gson.JsonObject;
import com.kaltura.client.Params;
import com.kaltura.client.enums.GenerateMetadataStatus;
import com.kaltura.client.types.ObjectBase;
import com.kaltura.client.utils.GsonParser;
import com.kaltura.client.utils.request.MultiRequestBuilder;

/**
 * This class was generated using exec.php
 * against an XML schema provided by Kaltura.
 * 
 * MANUAL CHANGES TO THIS CLASS WILL BE OVERWRITTEN.
 */

@SuppressWarnings("serial")
@MultiRequestBuilder.Tokenizer(GenerateMetadataBySubtitlesJob.Tokenizer.class)
public class GenerateMetadataBySubtitlesJob extends ObjectBase {
	
	public interface Tokenizer extends ObjectBase.Tokenizer {
		String id();
		String createDate();
		String updateDate();
		String fileName();
		String status();
		String errorMessage();
	}

	/**
	 * a Long type generated by the subtitles service and provides a unique identifier
	  for the object,              together with a metadataGenerationJob prefix which
	  is added by the aiMetadataGenerator service.              TODO: WHAT DOES IT
	  MEAN?
	 */
	private Long id;
	/**
	 * an Integer type representing the EPOCH time in seconds that the object was
	  created.
	 */
	private Long createDate;
	/**
	 * an Integer type representing the EPOCH time in seconds that the object was last
	  updated.
	 */
	private Long updateDate;
	/**
	 * a String type listing the file name that was uploaded.
	 */
	private String fileName;
	/**
	 * can be either Processing/Success/Failed, per the last status updated by the
	  aiMetadataGenerator micro-service.
	 */
	private GenerateMetadataStatus status;
	/**
	 * an optional String describing the error found in case that the Status is set to
	  Failed.
	 */
	private String errorMessage;

	// id:
	public Long getId(){
		return this.id;
	}
	// createDate:
	public Long getCreateDate(){
		return this.createDate;
	}
	// updateDate:
	public Long getUpdateDate(){
		return this.updateDate;
	}
	// fileName:
	public String getFileName(){
		return this.fileName;
	}
	// status:
	public GenerateMetadataStatus getStatus(){
		return this.status;
	}
	// errorMessage:
	public String getErrorMessage(){
		return this.errorMessage;
	}

	public GenerateMetadataBySubtitlesJob() {
		super();
	}

	public GenerateMetadataBySubtitlesJob(JsonObject jsonObject) throws APIException {
		super(jsonObject);

		if(jsonObject == null) return;

		// set members values:
		id = GsonParser.parseLong(jsonObject.get("id"));
		createDate = GsonParser.parseLong(jsonObject.get("createDate"));
		updateDate = GsonParser.parseLong(jsonObject.get("updateDate"));
		fileName = GsonParser.parseString(jsonObject.get("fileName"));
		status = GenerateMetadataStatus.get(GsonParser.parseString(jsonObject.get("status")));
		errorMessage = GsonParser.parseString(jsonObject.get("errorMessage"));

	}

	public Params toParams() {
		Params kparams = super.toParams();
		kparams.add("objectType", "KalturaGenerateMetadataBySubtitlesJob");
		return kparams;
	}


    public static final Creator<GenerateMetadataBySubtitlesJob> CREATOR = new Creator<GenerateMetadataBySubtitlesJob>() {
        @Override
        public GenerateMetadataBySubtitlesJob createFromParcel(Parcel source) {
            return new GenerateMetadataBySubtitlesJob(source);
        }

        @Override
        public GenerateMetadataBySubtitlesJob[] newArray(int size) {
            return new GenerateMetadataBySubtitlesJob[size];
        }
    };

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        super.writeToParcel(dest, flags);
        dest.writeValue(this.id);
        dest.writeValue(this.createDate);
        dest.writeValue(this.updateDate);
        dest.writeString(this.fileName);
        dest.writeInt(this.status == null ? -1 : this.status.ordinal());
        dest.writeString(this.errorMessage);
    }

    public GenerateMetadataBySubtitlesJob(Parcel in) {
        super(in);
        this.id = (Long)in.readValue(Long.class.getClassLoader());
        this.createDate = (Long)in.readValue(Long.class.getClassLoader());
        this.updateDate = (Long)in.readValue(Long.class.getClassLoader());
        this.fileName = in.readString();
        int tmpStatus = in.readInt();
        this.status = tmpStatus == -1 ? null : GenerateMetadataStatus.values()[tmpStatus];
        this.errorMessage = in.readString();
    }
}

