// ===================================================================================================
//                           _  __     _ _
//                          | |/ /__ _| | |_ _  _ _ _ __ _
//                          | ' </ _` | |  _| || | '_/ _` |
//                          |_|\_\__,_|_|\__|\_,_|_| \__,_|
//
// This file is part of the Kaltura Collaborative Media Suite which allows users
// to do with audio, video, and animation what Wiki platfroms allow them to do with
// text.
//
// Copyright (C) 2006-2020  Kaltura Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// @ignore
// ===================================================================================================
package com.kaltura.client.types;

import android.os.Parcel;
import com.google.gson.JsonObject;
import com.kaltura.client.Params;
import com.kaltura.client.enums.SubtitlesType;
import com.kaltura.client.types.ObjectBase;
import com.kaltura.client.utils.GsonParser;
import com.kaltura.client.utils.request.MultiRequestBuilder;

/**
 * This class was generated using exec.php
 * against an XML schema provided by Kaltura.
 * 
 * MANUAL CHANGES TO THIS CLASS WILL BE OVERWRITTEN.
 */

/**
 * A class representing the properties of an uploaded subtitles file.
 */
@SuppressWarnings("serial")
@MultiRequestBuilder.Tokenizer(Subtitles.Tokenizer.class)
public class Subtitles extends ObjectBase {
	
	public interface Tokenizer extends ObjectBase.Tokenizer {
		String id();
		String createDate();
		String fileName();
		String type();
		String language();
	}

	/**
	 * Read only. An ID generated by the subtitles service for the uploaded file.
	 */
	private Long id;
	/**
	 * Read only. An Integer type representing the EPOCH time in seconds that the file
	  was uploaded.
	 */
	private Long createDate;
	/**
	 * Mandatory. The name that will be associated with the uploaded file.
	 */
	private String fileName;
	/**
	 * Mandatory. The type of the subtitles file. Supported - Text, SRT, WebVTT.
	 */
	private SubtitlesType type;
	/**
	 * Mandatory. The language in which the subtitles are written.              It is
	  used in the LLM prompt to inform it what is the language it needs to analyze.
	 */
	private String language;

	// id:
	public Long getId(){
		return this.id;
	}
	// createDate:
	public Long getCreateDate(){
		return this.createDate;
	}
	// fileName:
	public String getFileName(){
		return this.fileName;
	}
	public void setFileName(String fileName){
		this.fileName = fileName;
	}

	public void fileName(String multirequestToken){
		setToken("fileName", multirequestToken);
	}

	// type:
	public SubtitlesType getType(){
		return this.type;
	}
	public void setType(SubtitlesType type){
		this.type = type;
	}

	public void type(String multirequestToken){
		setToken("type", multirequestToken);
	}

	// language:
	public String getLanguage(){
		return this.language;
	}
	public void setLanguage(String language){
		this.language = language;
	}

	public void language(String multirequestToken){
		setToken("language", multirequestToken);
	}


	public Subtitles() {
		super();
	}

	public Subtitles(JsonObject jsonObject) throws APIException {
		super(jsonObject);

		if(jsonObject == null) return;

		// set members values:
		id = GsonParser.parseLong(jsonObject.get("id"));
		createDate = GsonParser.parseLong(jsonObject.get("createDate"));
		fileName = GsonParser.parseString(jsonObject.get("fileName"));
		type = SubtitlesType.get(GsonParser.parseString(jsonObject.get("type")));
		language = GsonParser.parseString(jsonObject.get("language"));

	}

	public Params toParams() {
		Params kparams = super.toParams();
		kparams.add("objectType", "KalturaSubtitles");
		kparams.add("fileName", this.fileName);
		kparams.add("type", this.type);
		kparams.add("language", this.language);
		return kparams;
	}


    public static final Creator<Subtitles> CREATOR = new Creator<Subtitles>() {
        @Override
        public Subtitles createFromParcel(Parcel source) {
            return new Subtitles(source);
        }

        @Override
        public Subtitles[] newArray(int size) {
            return new Subtitles[size];
        }
    };

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        super.writeToParcel(dest, flags);
        dest.writeValue(this.id);
        dest.writeValue(this.createDate);
        dest.writeString(this.fileName);
        dest.writeInt(this.type == null ? -1 : this.type.ordinal());
        dest.writeString(this.language);
    }

    public Subtitles(Parcel in) {
        super(in);
        this.id = (Long)in.readValue(Long.class.getClassLoader());
        this.createDate = (Long)in.readValue(Long.class.getClassLoader());
        this.fileName = in.readString();
        int tmpType = in.readInt();
        this.type = tmpType == -1 ? null : SubtitlesType.values()[tmpType];
        this.language = in.readString();
    }
}

