name: Android Build and Publish

on:
  push:
    branches: '[0-9]+_[0-9]+_[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Tag
      run: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} sh .github/tag.sh
    - name: Build and Publish
      run: |
        BINTRAY_USER=${{ secrets.BINTRAY_USER }} BINTRAY_PASS=${{ secrets.BINTRAY_PASS }} sh .github/publish.sh
